[package]
name = "rip-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_sdl2_gl = "0.22.1"
rand = "^0.8.5"
sdl2 = "^0.35.0"
gl = "~0.14"

